<?php

/**
 * @file
 * Install, update, and uninstall functions for the ziggeo module.
 */

/**
 * Implements hook_field_schema().
 *
 * Define the schema for the field.
 */
function ziggeo_field_schema($field) {
  $columns = array(
    'token' => array(
      'type' => 'varchar',
      'length' => '128',
      'not null' => TRUE,
  ));
  return array(
    'columns' => $columns,
  );
}
